apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
  labels:
    app: kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
      - name: kube
        image: dinithm/helloword
        ports:
        - containerPort: 80
        imagePullPolicy: Never
---

apiVersion: v1
kind: Service
metadata:
  name: kube
spec:
  selector:
    app: kube
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer




